// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7AS-3oJJhu1y6ZsyBux-dwFVgqjEe7Cs',
    appId: '1:107426988760:web:872dc4110b8da68b59cdad',
    messagingSenderId: '107426988760',
    projectId: 'online-pharmacy-627ae',
    authDomain: 'online-pharmacy-627ae.firebaseapp.com',
    storageBucket: 'online-pharmacy-627ae.firebasestorage.app',
    measurementId: 'G-NS66Z5GMXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzIR9S0__sp4lfmQ-jyUrrHUD6AJz5SGM',
    appId: '1:107426988760:android:2bd8fdde6b7a919759cdad',
    messagingSenderId: '107426988760',
    projectId: 'online-pharmacy-627ae',
    storageBucket: 'online-pharmacy-627ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7pOlKXJEyVG0rpzsxpDK7MYiclVEXjPg',
    appId: '1:107426988760:ios:52021700ea2f37d359cdad',
    messagingSenderId: '107426988760',
    projectId: 'online-pharmacy-627ae',
    storageBucket: 'online-pharmacy-627ae.firebasestorage.app',
    iosBundleId: 'com.example.onlinePharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7AS-3oJJhu1y6ZsyBux-dwFVgqjEe7Cs',
    appId: '1:107426988760:web:1c4b3e9b81fcee1d59cdad',
    messagingSenderId: '107426988760',
    projectId: 'online-pharmacy-627ae',
    authDomain: 'online-pharmacy-627ae.firebaseapp.com',
    storageBucket: 'online-pharmacy-627ae.firebasestorage.app',
    measurementId: 'G-2X9QFJV3MD',
  );
}
